version: '3.8'

# ${variable} variable values can be found in .env
services:
  postgres:
    container_name: ${DOCKER_NAME}
    image: ${DOCKER_IMAGE}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DB_PORT}:${DB_PORT_MAP}"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: